### ISSUE TITLE
version dist/ only on release commit/tag

### ISSUE THREAD

**Issue by behaghel** [peter-mouland/web-caddy#103]
Bower wants you to store your resulting JS assets in your git repository. It's pragmatic but comes with too high of a price IMHO. Particularly on a project that will have a whole tree of JS files that get packaged into one asset for consumption. You give up on cherry-picking, PR have to be submitted after all other have been merged or they will systematically be conflicting. Last but not least, code review becomes a pain as you need to ignore most of the changes in the diff view...

The idea would be to create a new release option which when enabled would add a _pre_ and _post_ task to the regular release task.

**Pre release**: unignore `dist/`. That's enough I think as the release task as it stands now `add .` (I find it quite dangerous btw), so it will pick up `dist/`.

**Post release**: delete `dist/`, ignore it and commit with subject _Post-release vx.y.z_ or something like that.

I have most of it working. Testing in an automated fashion may be a bit of a challenge for me, happy to take advice.

Thoughts?

**Comment by peter-mouland** [comment]
the `add .` has been changed and is sitting in one of the many PR's that are waiting to be looked at.

I think you can add `dist` to `gitignore`, and then like the `gh-pages` and `_site` works, could a new `bower` branch be created to store the src and dist directories.  If this was what is git-tag'ed, would bower  still be able to use it?  the release step would then simply be `release: ['bower']`.
