### ISSUE TITLE
Images are not transferred to _site from demo

### ISSUE THREAD

**Issue by rosswarren** [peter-mouland/web-caddy#105]
To reproduce,

Create a new component and serve it. You will notice the Github icon 404s (images/Github-Mark-32px.png). This is because it is not transferred to _site.

**Comment by rosswarren** [comment]
For some reason I was expecting this to run when you start serve, it works fine if I run it separately.

**Comment by peter-mouland** [comment]
ah - yeah, you can put copy as part of the tasks object
```

    tasks: {
        copy: ['images'],
        build: ['sass', 'mustache', 'browserify'],
        serve: 'staticApp',
        test: 'karma',
        release: ['git', 'gh-pages', 'bower']
    },
```
and then add `caddy copy` to npm start if you want
