### ISSUE TITLE
do we want to test concatinated and/or minified code?

### ISSUE THREAD

**Issue by peter-mouland** [peter-mouland/web-caddy#61]
The current testing setup (as of v1.1.0) tests JS files individually.

The code that gets released (concatenate .js file and the minfied .min.js file) are therefore not tested.

Do we want to add an extra step to test .min.js file once all the individual tests have passed?

**Comment by behaghel** [comment]
As a release step that can't hurt, it'd get my vote.



—

**Comment by peter-mouland** [comment]
i dont think there is a way of testing the real .min.js file, because you'd then have to have two karma configs and this would be confusing and difficult to maintain.

At the moment, karma runs the tests individually. I think we'd have concat an index of all the tests so that the tests and, therefore, all code is browserified into a single file.  This wouldn't be the real .min.js file, but it would have gone through the same minification process. so i think it would be a valid test, answering the question 'did the minification break my code'.
