### ISSUE TITLE
Support --dry-run on release, improve logging.

### ISSUE THREAD

**Issue by behaghel** [peter-mouland/web-caddy#86]
We are all nervous at times on this key operation. Rehearsing makes it perfect.

Logging could be improved. My `directoryPrefix`/`target` was wrong due to a breaking change and I couldn't find the files I had uploaded on S3 because it only says 
```
S3::putObject "[Absolute path to file]" send
```
But it doesn't say where it has been sent.

The more explicit is the logging on the effects of the release process the better.

**Comment by peter-mouland** [comment]
sorted here: https://github.com/peter-mouland/web-caddy/commit/8b4bbb99c68b3c740ac4eb43bd9d1bdc498f0a4f

will be in the next release (probably beta.3)
