### ISSUE TITLE
support --verify url on release task

### ISSUE THREAD

**Issue by behaghel** [peter-mouland/web-caddy#88]
`--verify url-base` would try to GET the assets via the link passed as an argument and verify the presence of the right version of each files (e.g. md5).

**Comment by peter-mouland** [comment]
could you explain this a bit more, i'm not sure what the use case is?

**Comment by behaghel** [comment]
Feel free to reject if you don't see enough value or feel it's more a concern to be addressed on consumer project side.

The idea is that when you do a release, you want to ensure it's done and well done. To ease the process of checking this out, the component CLI could offer this argument and expose a hook where consumer projects could hang their validation steps.

Practically, the need arose while integrating the recent release improvements in the component-helper into sky-tags. Once done, I need to ask a peer to validate that my changes to sky-tags release process are good to merge. Automated this kind of test is not always easy and require some support from the release tool (component-helper in this case) but still a good idea. Once automated, it's actually useful to be able to use this testing to validate each release. Hence this issue.

I wouldn't say it's top priority but if it is a welcome idea, I may work on it. I like extremely robust release management.

**Comment by peter-mouland** [comment]
Sounds interesting, don't think I could take the lead but would be very
happy to see where this leads :)
